[package]
name = "grafo_termux"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web Framework
axum = "0.7"
tokio = { version = "1", features = ["full"] }

# Template Engine (HTML compilado)
askama = "0.12"
askama_axum = "0.4"

rust-embed = "8.0"   # Para embutir arquivos no exe
mime_guess = "2.0"   # Para saber se é JS, CSS ou Imagem automaticamente

# JSON
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Banco de Dados (SEM TLS para facilitar o estático)
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio"] }

# Arquivos estáticos (caso precise no futuro)
tower-http = { version = "0.5", features = ["fs"] }

# Otimização de Tamanho (Release Profile)
[profile.release]
strip = true  # Arranca símbolos (strip automático)
opt-level = "z"  # Otimiza para Tamanho (Size) em vez de Velocidade máxima
lto = true    # Link Time Optimization (Remove código morto de libs)
codegen-units = 1 # Otimiza melhor (demora um pouco mais pra compilar)
panic = "abort" # Remove lógica de "unwind" de erro (mais leve)