[package]
name = "grafo_termux"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web Framework
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1", features = ["full"] }

# Template Engine
askama = "0.12"
askama_axum = "0.4"

# Embed (A Mágica do Monólito)
rust-embed = "8.0"
mime_guess = "2.0"

# Otimização (Mantive igual)
[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"